/*
 * Name :- Chanuka Ashan Gunawardena
 * Lab Group :- 01
 * Module :- SO2
 * Lab :- 01
 * Task :- NUMBER GUESSING GAME
 */
package Task2;

import java.util.Scanner;
import java.util.Random;

public class Main {
    public static void main(String[] args){

        System.out.println("\nWELCOME!\n");
        System.out.println("Here you guess a number between 1 & 100 in which the computer might produce.");

        int number;
        int guessNumber;
        boolean gameRunning = true;

        Scanner scanner = new Scanner(System.in);

        while(gameRunning) {

                System.out.print("\nEnter the number you guess: ");
                guessNumber = scanner.nextInt();

                Random random1 = new Random();

                number = random1.nextInt(1, 101);

                System.out.println("The number generated by the computer: " + number);

            if(guessNumber == number) {
                System.out.println("CONGRATULATIONS you guessed CORRECT!");
                break;
            }
                else if(guessNumber < number){
                    System.out.println("You guessed TOO SMALL");
                } else if (guessNumber > number)
                {
                      System.out.println("You guessed TOO BIG");
            }

        }
        scanner.close();
    }
}
